version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  kubernetes:
    lang: runner-template-python3
    handler: ./kubernetes
    image: 564407622114.dkr.ecr.eu-west-1.amazonaws.com/actionstore/kubernetes
    annotations:
        topic: "kubernetes"
        com.openfaas.serviceaccount: default